//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol ClickEventDelegate <NSObject>

@optional
- (void)doubleClicked:(id)arg1 location:(struct CGPoint)arg2;
- (void)doubleClicked:(id)arg1;
- (void)singleClicked:(id)arg1;
@end



/*
@protocol UIWebViewDelegate <NSObject>

@optional
- (void)webView:(UIWebView *)arg1 didFailLoadWithError:(NSError *)arg2;
- (void)webViewDidFinishLoad:(UIWebView *)arg1;
- (void)webViewDidStartLoad:(UIWebView *)arg1;
- (_Bool)webView:(UIWebView *)arg1 shouldStartLoadWithRequest:(NSURLRequest *)arg2 navigationType:(long long)arg3;
@end*/

@class NSDate, NSDictionary, NSString, NSTextCheckingResult, NSTimeZone, NSURL, TTTAttributedLabel;

@protocol TTTAttributedLabelDelegate <NSObject>

@optional
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didLongPressLinkWithTextCheckingResult:(NSTextCheckingResult *)arg2 atPoint:(struct CGPoint)arg3;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didLongPressLinkWithTransitInformation:(NSDictionary *)arg2 atPoint:(struct CGPoint)arg3;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didLongPressLinkWithDate:(NSDate *)arg2 timeZone:(NSTimeZone *)arg3 duration:(double)arg4 atPoint:(struct CGPoint)arg5;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didLongPressLinkWithDate:(NSDate *)arg2 atPoint:(struct CGPoint)arg3;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didLongPressLinkWithPhoneNumber:(NSString *)arg2 atPoint:(struct CGPoint)arg3;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didLongPressLinkWithAddress:(NSDictionary *)arg2 atPoint:(struct CGPoint)arg3;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didLongPressLinkWithURL:(NSURL *)arg2 atPoint:(struct CGPoint)arg3;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didSelectLinkWithTextCheckingResult:(NSTextCheckingResult *)arg2;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didSelectLinkWithTransitInformation:(NSDictionary *)arg2;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didSelectLinkWithDate:(NSDate *)arg2 timeZone:(NSTimeZone *)arg3 duration:(double)arg4;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didSelectLinkWithDate:(NSDate *)arg2;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didSelectLinkWithPhoneNumber:(NSString *)arg2;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didSelectLinkWithAddress:(NSDictionary *)arg2;
- (void)attributedLabel:(TTTAttributedLabel *)arg1 didSelectLinkWithURL:(NSURL *)arg2;
@end


#import <UIKit/UITableViewCell.h>


@class MLActivityIndicator, MLClickDetectedView, MLDraftLabel, MLPhotoStoryLabel, MLRoundImageView, MLSmoothVideoLoopViewController, MLTappedHollowPaddingLabel, MLTappedLabel, MarqueeLabel, Musical, NSIndexPath, NSLayoutConstraint, NSString, TTTAttributedLabel, UIButton, UIImageView, UILabel, UITableViewController, UIView;

@interface MLMusicalTableViewCell : UITableViewCell <TTTAttributedLabelDelegate, UIWebViewDelegate, ClickEventDelegate>
{
    UILabel *placeHolderLabel;
    UIButton *placeHolderButton;
    _Bool _shouldAutoPlayAfterDownload;
    _Bool _libraryView;
    _Bool _nonfeedsView;
    _Bool _defaultMusical;
    NSIndexPath *_indexPath;
    Musical *_musical;
    MLSmoothVideoLoopViewController *_player;
    MLActivityIndicator *_downloadingIndicator;
    UIImageView *_maskViewInner;
    UIImageView *_backgroundImageView;
    //CDUnknownBlockType _tagTappedBlock;
    //CDUnknownBlockType _avatarTappedBlock;
    //CDUnknownBlockType _featuredTappedBlock;
    //CDUnknownBlockType _commentsTappedBlock;
    UITableViewController *_parentTable;
    NSLayoutConstraint *_songInfoWidthConstraint;
    UIView *_videoLayer;
    UIImageView *_maskViewTopNew;
    UIView *_maskViewTopNewLayer;
    MLClickDetectedView *_pageDetails;
    MarqueeLabel *_songInfoLabel;
    TTTAttributedLabel *_captionLabel;
    UIButton *_shareButton;
    UIButton *_likeButton;
    UIButton *_commentsButton;
    UILabel *_likeNumLabel;
    UILabel *_commentsNumLabel;
    MLRoundImageView *_userAvatarImageView;
    UIView *_photoStoryMask;
    UIImageView *_photoStoryImageMask;
    UIImageView *_photoStoryImageMaskLayer;
    MLTappedLabel *_musician;
    MLTappedLabel *_promoted;
    MLTappedHollowPaddingLabel *_reasonLabel;
    MLTappedLabel *_usernameLabel;
    MLRoundImageView *_repostAvatarImageView;
    UILabel *_shoutoutLabel;
    MLDraftLabel *_draftMarkLabel;
    MLDraftLabel *_photoStoryLabel;
    MLPhotoStoryLabel *_liveMomentLabel;
    UIButton *_moreActionButton;
    NSLayoutConstraint *_songTitleBottomConstraint;
    NSLayoutConstraint *_moreButtonBottomConstraint;
    UIView *_bannedMusicalMask;
    UILabel *_partyTitleLabel;
    UILabel *_viewerLabel;
}

@property(nonatomic) __weak UILabel *viewerLabel; // @synthesize viewerLabel=_viewerLabel;
@property(nonatomic) __weak UILabel *partyTitleLabel; // @synthesize partyTitleLabel=_partyTitleLabel;
@property(nonatomic) __weak UIView *bannedMusicalMask; // @synthesize bannedMusicalMask=_bannedMusicalMask;
@property(nonatomic) __weak NSLayoutConstraint *moreButtonBottomConstraint; // @synthesize moreButtonBottomConstraint=_moreButtonBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *songTitleBottomConstraint; // @synthesize songTitleBottomConstraint=_songTitleBottomConstraint;
@property(nonatomic) __weak UIButton *moreActionButton; // @synthesize moreActionButton=_moreActionButton;
@property(nonatomic) __weak MLPhotoStoryLabel *liveMomentLabel; // @synthesize liveMomentLabel=_liveMomentLabel;
@property(nonatomic) __weak MLDraftLabel *photoStoryLabel; // @synthesize photoStoryLabel=_photoStoryLabel;
@property(nonatomic) __weak MLDraftLabel *draftMarkLabel; // @synthesize draftMarkLabel=_draftMarkLabel;
@property(nonatomic) __weak UILabel *shoutoutLabel; // @synthesize shoutoutLabel=_shoutoutLabel;
@property(nonatomic) __weak MLRoundImageView *repostAvatarImageView; // @synthesize repostAvatarImageView=_repostAvatarImageView;
@property(nonatomic) __weak MLTappedLabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(nonatomic) __weak MLTappedHollowPaddingLabel *reasonLabel; // @synthesize reasonLabel=_reasonLabel;
@property(nonatomic) __weak MLTappedLabel *promoted; // @synthesize promoted=_promoted;
@property(nonatomic) __weak MLTappedLabel *musician; // @synthesize musician=_musician;
@property(nonatomic) __weak UIImageView *photoStoryImageMaskLayer; // @synthesize photoStoryImageMaskLayer=_photoStoryImageMaskLayer;
@property(nonatomic) __weak UIImageView *photoStoryImageMask; // @synthesize photoStoryImageMask=_photoStoryImageMask;
@property(nonatomic) __weak UIView *photoStoryMask; // @synthesize photoStoryMask=_photoStoryMask;
@property(nonatomic) __weak MLRoundImageView *userAvatarImageView; // @synthesize userAvatarImageView=_userAvatarImageView;
@property(nonatomic) __weak UILabel *commentsNumLabel; // @synthesize commentsNumLabel=_commentsNumLabel;
@property(nonatomic) __weak UILabel *likeNumLabel; // @synthesize likeNumLabel=_likeNumLabel;
@property(nonatomic) __weak UIButton *commentsButton; // @synthesize commentsButton=_commentsButton;
@property(nonatomic) __weak UIButton *downloadButton;
@property(nonatomic) __weak UIButton *likeButton; // @synthesize likeButton=_likeButton;
@property(nonatomic) __weak UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(nonatomic) __weak TTTAttributedLabel *captionLabel; // @synthesize captionLabel=_captionLabel;
@property(nonatomic) __weak MarqueeLabel *songInfoLabel; // @synthesize songInfoLabel=_songInfoLabel;
@property(nonatomic) __weak MLClickDetectedView *pageDetails; // @synthesize pageDetails=_pageDetails;
@property(nonatomic) __weak UIView *maskViewTopNewLayer; // @synthesize maskViewTopNewLayer=_maskViewTopNewLayer;
@property(nonatomic) __weak UIImageView *maskViewTopNew; // @synthesize maskViewTopNew=_maskViewTopNew;
@property(nonatomic) __weak UIView *videoLayer; // @synthesize videoLayer=_videoLayer;
@property(nonatomic) __weak NSLayoutConstraint *songInfoWidthConstraint; // @synthesize songInfoWidthConstraint=_songInfoWidthConstraint;
@property(nonatomic) __weak UITableViewController *parentTable; // @synthesize parentTable=_parentTable;
@property(nonatomic) _Bool defaultMusical; // @synthesize defaultMusical=_defaultMusical;
@property(nonatomic) _Bool nonfeedsView; // @synthesize nonfeedsView=_nonfeedsView;
@property(nonatomic) _Bool libraryView; // @synthesize libraryView=_libraryView;
//@property(copy, nonatomic) CDUnknownBlockType commentsTappedBlock; // @synthesize commentsTappedBlock=_commentsTappedBlock;
//@property(copy, nonatomic) CDUnknownBlockType featuredTappedBlock; // @synthesize featuredTappedBlock=_featuredTappedBlock;
//@property(copy, nonatomic) CDUnknownBlockType avatarTappedBlock; // @synthesize avatarTappedBlock=_avatarTappedBlock;
//@property(copy, nonatomic) CDUnknownBlockType tagTappedBlock; // @synthesize tagTappedBlock=_tagTappedBlock;
@property(nonatomic) _Bool shouldAutoPlayAfterDownload; // @synthesize shouldAutoPlayAfterDownload=_shouldAutoPlayAfterDownload;
@property(nonatomic) __weak UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) __weak UIImageView *maskViewInner; // @synthesize maskViewInner=_maskViewInner;
@property(nonatomic) __weak MLActivityIndicator *downloadingIndicator; // @synthesize downloadingIndicator=_downloadingIndicator;
@property(retain, nonatomic) MLSmoothVideoLoopViewController *player; // @synthesize player=_player;
@property(nonatomic) __weak Musical *musical; // @synthesize musical=_musical;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
//- (void).cxx_destruct;
- (void)followFriendTapped:(id)arg1;
- (void)commentChanged:(id)arg1;
- (void)shareMusical:(id)arg1;
- (void)moreAction:(id)arg1;
- (void)viewComments:(id)arg1;
- (void)showLikeNumber;
- (void)likeCurrentMusical:(id)arg1 action:(id)arg2;
- (void)unlikeCurrentMusical:(id)arg1;
- (void)like:(id)arg1;
- (void)updateLikeStatus;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)failedDownloadVideo:(id)arg1;
- (void)failedDownloadCover:(id)arg1;
- (void)updateDownloadVideoProgress:(float)arg1;
- (void)downloadVideoFinished:(id)arg1;
- (void)downloadCoverFinished:(id)arg1;
- (void)setMaskImage:(id)arg1 videoCached:(_Bool)arg2;
- (void)hidePlayer:(_Bool)arg1;
- (void)hideDetail:(_Bool)arg1;
- (void)configMetaInfoCaption:(id)arg1;
- (void)configMetaInfoSonginfo:(id)arg1;
- (void)configMetaInfoFeatured:(id)arg1;
- (void)configMaskView;
- (void)configMetaInfoButtons:(id)arg1;
- (void)configMetaInfoMusical:(id)arg1;
- (void)configureWithIndexPath:(id)arg1 object:(id)arg2;
- (_Bool)isMusicalBanned:(id)arg1;
- (void)layoutSubviews;
- (void)pause;
- (void)playWithAnimation:(_Bool)arg1;
- (void)configAsset;
- (void)setupDefaultFollowHolder;
- (void)continuePlay;
- (void)startPlay;
- (void)dealloc;
- (void)singleClicked:(id)arg1;
- (void)prepareForReuse;
- (void)doubleClicked:(id)arg1 location:(struct CGPoint)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)photoStoryAnimationState;
- (void)setUpPhotoStoryMask;
- (void)setUp;
- (void)awakeFromNib;
- (void)updateConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
//added by me
- (void)setButton;
- (void)saveVideo;


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long int/*hash*/;
@property(readonly) Class superclass;

@end
