//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MLTappedImageView.h"

@class NSLayoutConstraint;

@interface MLRoundImageView : MLTappedImageView
{
    NSLayoutConstraint *_widthConstrait;
}

@property(retain, nonatomic) NSLayoutConstraint *widthConstrait; // @synthesize widthConstrait=_widthConstrait;
//- (void).cxx_destruct;
- (void)setUp;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end
