//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "YYAnimatedImageView.h"

@interface MLTappedImageView : UIImageView
{
    _Bool _noNeedLogin;
    id _avatarTappedBlock;
    id _imageTapped;
}

@property(nonatomic) _Bool noNeedLogin; // @synthesize noNeedLogin=_noNeedLogin;
@property(copy, nonatomic) id imageTapped; // @synthesize imageTapped=_imageTapped;
@property(copy, nonatomic) id avatarTappedBlock; // @synthesize avatarTappedBlock=_avatarTappedBlock;
//- (void).cxx_destruct;
- (void)handleSingleTap:(id)arg1;
- (void)setUp;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end
