//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface Musical
{
}

+ (void)deleteOnServerByBID:(id)arg1 successBlock:(id)arg2;
+ (void)listRandomMusical:(id)arg1 failureBlock:(id)arg2 needNumCheck:(_Bool)arg3;
+ (void)attatchRandomUniqueTime:(id)arg1;
+ (id)nextRandomMusical;
+ (id)getByIDLocal:(id)arg1;
+ (id)getByBIDLocal:(id)arg1;
+ (id)getByID:(id)arg1 successBlock:(id)arg2 failureBlock:(id)arg3;
+ (id)getByMusicalID:(id)arg1;
+ (id)getByMusicalID:(id)arg1 toLocalContext:(_Bool)arg2;
+ (id)getByID:(id)arg1 toLocalContext:(_Bool)arg2 successBlock:(id)arg3 failureBlock:(id)arg4;
- (void)bindToCateId:(id)arg1 success:(id)arg2 fail:(id)arg3;
- (_Bool)shouldBindCategoryAfterUpload;
- (_Bool)treatAsCategory;
- (id)category;
- (_Bool)isCategory;
- (id)bid;
- (void)clearCachedFiles;
- (void)clearLocalFiles;
- (void)deleteLocalMusical;
- (id)watermarkMovieURLFullPath;
- (_Bool)firstFrameURLIsCached;
- (id)firstFrameURLCachePath;
- (id)firstFrameURLRelativeURL;
- (id)firstFrameURLFileName;
- (id)firstFrameURLFullURL;
- (id)animatedCoverURLFullPath;
- (id)firstFrameURLFullPath;
- (id)firstFrameURLFullName;
- (_Bool)movieURLIsCached;
- (id)movieURLCachePath;
- (id)movieURLRelativeURL;
- (unsigned long long)fileSizeValue;
- (id)fileSize;
- (id)shareLink;
- (id)movieURLFullPathForSocial:(unsigned long long)arg1;
- (id)movieURLSocialPathByAppendSuffix:(id)arg1 social:(unsigned long long)arg2;
- (id)movieURLFileName;
- (id)movieURLLocalPath;
- (id)movieURLFullURL;
- (id)movieURLFullPath;
- (id)movieURLFullName;
- (void)postOnlinePrivate:(id)arg1;
- (void)saveOnline:(id)arg1;
- (void)post:(id)arg1;
- (void)reportAbuse:(id)arg1 withComment:(id)arg2 category:(long long)arg3;
- (void)deleteRemoteMusical;
- (void)deleteOnServer:(id)arg1;
- (void)dePromote:(id)arg1;
- (void)removeFromFeaturePool:(id)arg1;
- (void)pinToCateogryTopWithSuccess:(id)arg1;
- (void)removeFromTag:(id)arg1 success:(id)arg2;
- (void)removeFromPopularNow:(id)arg1;
- (void)promoteAll:(id)arg1 immediate:(_Bool)arg2;
- (void)promoteToRegions:(id)arg1 immediate:(_Bool)arg2 completeBlcok:(id)arg3;
- (void)promoteToScope:(id)arg1 immediate:(_Bool)arg2 completeBlcok:(id)arg3;
- (void)read:(id)arg1;
- (void)unlike:(id)arg1 failure:(id)arg2;
- (void)like:(id)arg1 failure:(id)arg2;
- (void)copyFrom:(id)arg1;
- (id)mine;
- (_Bool)isOnlineMusical;
- (void)clearBackup:(id)arg1;
- (void)restoreFromBackup:(id)arg1;
- (id)backup;
- (_Bool)isPublish;
- (_Bool)isOnlinePrivate;
- (_Bool)isPrivate;
- (unsigned long long)defaultDisableFuntionsOptionInPreview;
- (_Bool)canSendViaDirectly;
- (_Bool)shouldStreamVideo;
- (_Bool)canDuet;
- (_Bool)showUploadingPercent;
- (_Bool)disablePostInSongDetail;

@end
